package constant

const (
	PERMISSION_ALL        string = "ALL"
	PERMISSION_FACULTY    string = "FACULTY"
	PERMISSION_INDIVIDUAL string = "INDIVIDUAL"
	PERMISSION_NONE       string = "NONE"
)

var PERMISSION_LIST = [...]string{PERMISSION_ALL, PERMISSION_FACULTY, PERMISSION_INDIVIDUAL, PERMISSION_NONE}
